#!/bin/sh

# Set these paths appropriately

BIN=/Users/mithun/agro/statnlp539/muenchenTagger/bin
CMD=/Users/mithun/agro/statnlp539/muenchenTagger/cmd
LIB=/Users/mithun/agro/statnlp539/muenchenTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
